name: aerosol-cloud-interactions-deposition-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mystmd
  - cookiecutter
  - act-atmos
  - cftime
  - xarray
  - matplotlib
  - metpy
  - tobac
  - arm_pyart